apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: certificate-authority-service
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Standalone CAS (Agent Cloud)
    version: 1.0.12
    source:
      repo: https://github.com/vandnagarggoogle/terraform-google-cas.git
      sourceType: git
      dir: /modules/standalone-cas
    actuationTool:
      flavor: Terraform
      version: ">= 1.5.7"
  interfaces:
    variables:
      - name: project_id
        varType: string
        required: true
      - name: location
        varType: string
        required: true
      - name: ca_pool_config
        varType: |-
          object({
            create_pool = optional(object({
              name            = string
              enterprise_tier = optional(bool, false)
            }))
            use_pool = optional(object({
              id = string
            }))
          })
        required: true
      - name: ca_configs
        varType: |-
          map(object({
            is_ca                                  = optional(bool, true)
            deletion_protection                    = optional(bool, false)
            skip_grace_period                      = optional(bool, true)
            ignore_active_certificates_on_deletion = optional(bool, false)
            subject = object({
              common_name  = string
              organization = string
            })
            key_usage = object({
              cert_sign   = optional(bool, true)
              crl_sign    = optional(bool, true)
              server_auth = optional(bool, true)
            })
            key_spec = object({
              algorithm = optional(string, "RSA_PKCS1_2048_SHA256")
            })
          }))
        required: false
      - name: iam
        varType: |-
          map(object({
            role   = string
            member = string
          }))
        required: false
    outputs:
      - name: ca_pool_id
        type: string
      - name: ca_chains
        description: The CA chains in PEM format.
      - name: ca_ids
        description: The CA ids.
      - name: ca_pool
        description: The CA pool resource.
      - name: cas
        description: The Certificate Authority resources.