apiVersion: designcenter.googleapis.com/v1alpha1
kind: Component
metadata:
  name: certificate-authority-service
spec:
  origin:
    source:
      git:
        # Update with your forked repo URL
        remote: https://github.com/your-org/your-forked-repo.git
        directory: modules/standalone-cas
        branch: main
  actuationTool:
    flavor: Terraform
    version: ">= 1.5.7"
  parameters:
    - name: project_id
      type: STRING
    - name: location
      type: STRING
    - name: ca_pool_config
      type: OBJECT
    - name: ca_configs
      type: MAP
  outputs:
    - name: ca_pool_id
      type: STRING
