apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: certificate-authority-service
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Standalone CAS (Agent Cloud)
    source:
      repo: https://github.com/vandnagarggoogle/terraform-google-cas.git
      sourceType: git
      dir: /modules/standalone-cas
    actuationTool:
      flavor: Terraform
      version: ">= 1.5.7"
  interfaces:
    variables:
      - name: project_id
        varType: string
        required: true
      - name: location
        varType: string
        required: true
      - name: ca_pool_config
        varType: object
      - name: ca_configs
        varType: map
    outputs:
      - name: ca_pool_id
        type: string
